=== wangfujia/Moira/Core/Config Files/FilesDispatcher.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="FilesDispatcherConfiguration"
    elementFormDefault="unqualified"
    attributeFormDefault="unqualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://BAFactory.net/schemas/FilesDispatcher/"
    targetNamespace="http://BAFactory.net/schemas/FilesDispatcher/"
>

  <xs:complexType name="AssemblyInfoElement">
    <xs:attribute name="Type" type="xs:string"  use="required" />
    <xs:attribute name="Class" type="xs:string"  use="required"/>
    <xs:attribute name="Assembly" type="xs:string"  use="required"/>
    <xs:attribute name="PublicKeyToken" type="xs:string" />
    <xs:attribute name="Culture" type="xs:string" />
    <xs:attribute name="Version" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="PatternElement">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="IsRegEx" type="xs:boolean" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name ="ParameterElement">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Name" />
        <xs:attribute name="Analyzer" />
        <xs:attribute name="AttributeName" />
        <xs:attribute name="AttributeType" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:element name="Configuration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Assemblies" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Steps">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="Step" type="AssemblyInfoElement" />
                  </xs:all>
                </xs:complexType>
              </xs:element>
              <xs:element name="FileAnalyzers">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="Step"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>
              <xs:element name="LogProvider" type="AssemblyInfoElement" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Tasks" minOccurs="1" >
          <xs:complexType>
            <xs:sequence>
              <xs:element name="BaseDirectory" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Path" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="Pattern"  type="PatternElement" minOccurs="1" maxOccurs="1" />
                    <xs:element name="Interval" type="xs:unsignedLong" minOccurs="1" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="StepsGroups" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="StepsGroup">
                      <xs:complexType>
                        <xs:all>
                          <xs:element name="Step" minOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Pattern" type="PatternElement" minOccurs="1" maxOccurs="1"/>
                                <xs:element name="Parameters" minOccurs="1" maxOccurs="1">
                                  <xs:complexType>
                                    <xs:all>
                                      <xs:element name="Parameter" type="ParameterElement" />
                                    </xs:all>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:all>
                      </xs:complexType>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Id" type="xs:string" use="required" />
            <xs:attribute name="Enabled" type="xs:boolean" use="required"/>
            <xs:attribute name="RunOnStartUp" type="xs:boolean" use="required"/>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== wangfujia/Moira/Core/Config Files/FilesDispatcher.xml
<?xml version="1.0" encoding="utf-8" ?>
<Configuration
  xmlns="http://BAFactory.net/schemas/FilesDispatcher"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://BAFactory.net/schemas/ FilesDispatcher.xsd">
  <Assemblies>
    <Steps>
      <Step Type="Copy" Class="BAFactory.Moira.Steps.Copy" Assembly="BAFactory.Moira.Core" PublicKeyToken="null" Culture="neutral" Version="1.0.0.0" />
      <Step Type="Move" Class="BAFactory.Moira.Steps.Move" Assembly="BAFactory.Moira.Core" PublicKeyToken="null" Culture="neutral" Version="1.0.0.0" />
      <Step Type="CreateFolder" Class="BAFactory.Moira.Steps.CreateFolder" Assembly="BAFactory.Moira.Core" PublicKeyToken="null" Culture="neutral" Version="1.0.0.0" />
    </Steps>
    <FileAnalyzers>
      <FileAnalyzer Type="ExifTags" Class="BAFactory.Moira.FileAnalyzers.ExifTagFileAnalyzer" Assembly="BAFactory.Moira.Core" PublicKeyToken="null" Culture="neutral" Version="1.0.0.0"  />
      <FileAnalyzer Type="FileAttribute" Class="BAFactory.Moira.FileAnalyzers.AttributesFileAnalyzer" Assembly="BAFactory.Moira.Core" PublicKeyToken="null" Culture="neutral" Version="1.0.0.0"  />
      <FileAnalyzer Type="WpFileName" Class="BAFactory.Moira.FileAnalyzers.WpVideoNameAnalyzer" Assembly="BAFactory.Moira.Core" PublicKeyToken="null" Culture="neutral" Version="1.0.0.0"  />
    </FileAnalyzers>
    <LogProvider Type="TextFileLog" Class="BAFactory.Moira.Core.Log.TextFileLogProvider" Assembly="BAFactory.Moira.Core" PublicKeyToken="null" Culture="neutral" Version="1.0.0.0" />
    <Dispatcher Type="AsyncDispatcher" Class="BAFactory.Moira.Core.AsyncDispatcher" Assembly="BAFactory.Moira.Core" PublicKeyToken="null" Culture="neutral" Version="1.0.0.0" />
  </Assemblies>

  <Tasks>
    <Task id="OrderPictures" enabled="true" runonstartup="true">
      <BaseDirectory>
        <Path><![CDATA[d:\temp]]></Path>
        <Pattern isRegEx="false"><![CDATA[*.mov]]></Pattern>
        <Interval>10</Interval>
      </BaseDirectory>
      <StepsGroups>
        <StepsGroup id="ByDateAquired" enabled="true" breakcondition="OnSuccess">
          <Step Type="CreateFolder" id="CreateFolderByDateAquired" breakcondition="OnError">
            <Pattern isRegEx="false"><![CDATA[*.*]]></Pattern>
            <Parameters>
              <Parameter name="FullDirectoryName" analyzer="ExifTags" attributeName="DateTime" attributeType="System.DateTime" ><![CDATA[d:\temp\{yyyy - MM - dd}]]></Parameter>
            </Parameters>
          </Step >
          <Step Type="Move" id="MoveFileByDateTaken">
            <Pattern isRegEx="false"><![CDATA[*.*]]></Pattern>
            <Parameters>
              <Parameter name="DestinationPath" fromLastResult="true"></Parameter>
            </Parameters>
          </Step >
        </StepsGroup>
        <StepsGroup id="ByDateTaken" enabled="true" breakcondition="OnSuccess">
          <Step Type="CreateFolder" id="CreateFolderByDateTaken" breakcondition="OnError">
            <Pattern isRegEx="false"><![CDATA[*.*]]></Pattern>
            <Parameters>
              <Parameter name="FullDirectoryName" analyzer="ExifTags" attributeName="DateTimeOriginal" attributeType="System.DateTime" ><![CDATA[d:\temp\{yyyy - MM - dd}]]></Parameter>
            </Parameters>
          </Step >
          <Step Type="Move" id="MoveFileByDateTaken">
            <Pattern isRegEx="false"><![CDATA[*.*]]></Pattern>
            <Parameters>
              <Parameter name="DestinationPath" fromLastResult="true"></Parameter>
            </Parameters>
          </Step >
        </StepsGroup>
        <StepsGroup id="ByDateModified" enabled="true" breakcondition="OnSuccess">
          <Step Type="CreateFolder" id="CreateFolderByDateModified" breakcondition="OnError">
            <Pattern isRegEx="false"><![CDATA[*.*]]></Pattern>
            <Parameters>
              <Parameter name="FullDirectoryName" analyzer="FileAttribute" attributeName="LastWriteTime" attributeType="System.DateTime" ><![CDATA[d:\temp\{yyyy - MM - dd}]]></Parameter>
            </Parameters>
          </Step >
          <Step Type="Move" id="MoveFileByDateModified">
            <Pattern isRegEx="false"><![CDATA[*.*]]></Pattern>
            <Parameters>
              <Parameter name="DestinationPath" fromLastResult="true"></Parameter>
            </Parameters>
          </Step >
        </StepsGroup >
        <StepsGroup id="ByWpFileName" enabled="true" breakcondition="OnSuccess">
          <Step Type="CreateFolder" id="CreateFolderByDateModified" breakcondition="OnError">
            <Pattern isRegEx="false"><![CDATA[*.*]]></Pattern>
            <Parameters>
              <Parameter name="FullDirectoryName" analyzer="WpFileName" attributeName="Name" attributeType="System.DateTime" ><![CDATA[d:\temp\{yyyy - MM - dd}]]></Parameter>
            </Parameters>
          </Step >
          <Step Type="Move" id="MoveFileByWpFileName">
            <Pattern isRegEx="false"><![CDATA[*.*]]></Pattern>
            <Parameters>
              <Parameter name="DestinationPath" fromLastResult="true"></Parameter>
            </Parameters>
          </Step >
        </StepsGroup >
      </StepsGroups>
    </Task>
  </Tasks>
</Configuration>
